### PR TITLE
Handle corner case when likelihood is zero.

### PR DESCRIPTION
**Pull request by sl9289**
Add a small number 1e-200 to likelihood values to prevent applying log function on zeros.

### CODE REVIEW

**Comment by arteagac** [comment]
Dear @sl9289, thank you very much for submitting this pull request. This strategy of adding a very small number to the likelihood seems reasonable to me. I will just double check that it does not break any functionality in the codebase and get back to you. 

Dear @jhelvy, I just wanted to ask for your insight into adding a small number to the likelihood to avoid corner cases of undefined log of zero. I think this should be fine but I wanted to quickly run it by you to ensure that this does not mask potential errors that should be thrown when the utilities result in a log of zero.

**Comment by jhelvy** [comment]
I haven't checked the code, but where is the addition happening? If it's being added to the utility such that it's basically u = u + epsilon, then that should be fine because utility only has relative meaning, so any number for epsilon shouldn't affect the choice probabilities.

**Comment by arteagac** [comment]
Thank you, John. The addition of the epsilon does not happen at the utilities but at the end of the log-likelihood function, right before computing the log of the likelihood (see short code snippet below). This addition seeks to avoid potential errors due to log of zeros. 


```python
    loglik = np.log(lik + 1e-200)
    return -loglik
```

**Comment by jhelvy** [comment]
Okay that seems reasonable, I don't see how that would create any problems. The optimization is looking for relative changes in the log-likelihood, so if the small value is always added then it should still converge just the same, and it's so small that it won't likely even be perceptible to the user. That is, if a user wanted to compare the LL from different runs or something, they wouldn't be able to notice a difference.

**Comment by arteagac** [comment]
Yes, I also think it is reasonable. Thanks a lot, John, for providing your insights into this. 

Dear @sl9289, I will proceed to merge this pull request and release the update to PyPi with a minor version change (v0.2.8).

**Pull request merged**
